# Generated by Django 5.0.9 on 2026-07-25 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand_quantity', models.IntegerField(default=0, help_text='Physically in the warehouse')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Held for unpaid/processing orders')),
                ('sold_quantity', models.IntegerField(default=0, help_text='Lifetime units sold, for reporting')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('adjustment', 'Manual adjustment'), ('reservation', 'Reservation'), ('reservation_release', 'Reservation release'), ('sale', 'Sale'), ('return', 'Return')], max_length=25)),
                ('on_hand_delta', models.IntegerField(default=0)),
                ('reserved_delta', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('resulting_on_hand', models.IntegerField()),
                ('resulting_reserved', models.IntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
            },
        ),
    ]
